"""
Update Freshservice tickets from cached investigations
"""

import sqlite3
import json
import os
import requests
import time
from config import FRESHSERVICE_URL

def update_freshservice_from_cache(ticket_ids=None):
    """
    Update Freshservice tickets using cached investigation results
    
    Args:
        ticket_ids: List of specific ticket IDs, or None for all cached tickets
    """
    
    # Get API key
    api_key = os.getenv('FRESHSERVICE_API_KEY')
    if not api_key:
        raise ValueError("FRESHSERVICE_API_KEY not set")
    
    # Connect to cache
    conn = sqlite3.connect('investigations.db')
    
    if ticket_ids:
        # Specific tickets
        placeholders = ','.join('?' * len(ticket_ids))
        query = f"SELECT ticket_id, data FROM investigations WHERE ticket_id IN ({placeholders})"
        rows = conn.execute(query, ticket_ids).fetchall()
    else:
        # All tickets
        rows = conn.execute("SELECT ticket_id, data FROM investigations").fetchall()
    
    conn.close()
    
    print(f"\n{'='*70}")
    print(f"UPDATING FRESHSERVICE FROM CACHE")
    print(f"{'='*70}")
    print(f"Tickets to update: {len(rows)}\n")
    
    updated = 0
    failed = 0
    skipped = 0
    
    for ticket_id, data_json in rows:
        try:
            result = json.loads(data_json)
            
            # Skip wrong escalations
            if result.get('wrong_escalation'):
                print(f"#{ticket_id}: ⏭️  Skipped (wrong escalation)")
                skipped += 1
                continue
            
            # Skip failed investigations
            if not result.get('success'):
                print(f"#{ticket_id}: ⏭️  Skipped (investigation failed)")
                skipped += 1
                continue
            
            # Get priority
            priority = result.get('priority', 2)
            
            # Build internal note
            fraud_status = result.get('fraud_status', 'Unknown')
            confidence = result.get('confidence', 0)
            summary = result.get('investigation_summary', '')
            case_outcome = result.get('case_outcome', 'Unknown')
            
            note = f"""🤖 AI Investigation (Auto-generated)

Status: {fraud_status}
Confidence: {confidence:.0%}
Outcome: {case_outcome}

Summary: {summary}

---
Generated by M-KOPA Fraud Investigation Engine v2.0"""
            
            # Update Freshservice
            url = f"{FRESHSERVICE_URL}/tickets/{ticket_id}"
            
            # Update priority
            response = requests.put(
                url,
                auth=(api_key, 'X'),
                json={'priority': priority},
                timeout=30
            )
            response.raise_for_status()
            
            # Add internal note
            notes_url = f"{FRESHSERVICE_URL}/tickets/{ticket_id}/notes"
            response = requests.post(
                notes_url,
                auth=(api_key, 'X'),
                json={
                    'body': note,
                    'private': True
                },
                timeout=30
            )
            response.raise_for_status()
            
            priority_labels = {1: '🟢 Low', 2: '🟡 Medium', 3: '🟠 High', 4: '🔴 Critical'}
            print(f"#{ticket_id}: ✅ Updated - {priority_labels.get(priority, 'Unknown')} priority")
            updated += 1
            
            # Rate limiting
            time.sleep(0.5)
            
        except Exception as e:
            print(f"#{ticket_id}: ❌ Failed - {e}")
            failed += 1
    
    # Summary
    print(f"\n{'='*70}")
    print("UPDATE SUMMARY")
    print(f"{'='*70}")
    print(f"✅ Updated: {updated}")
    print(f"❌ Failed: {failed}")
    print(f"⏭️  Skipped: {skipped}")
    print(f"Total: {len(rows)}")


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == '--file':
        # Read from file
        with open(sys.argv[2]) as f:
            ticket_ids = [line.strip() for line in f if line.strip()]
        update_freshservice_from_cache(ticket_ids)
    elif len(sys.argv) > 1:
        # From command line args
        ticket_ids = sys.argv[1:]
        update_freshservice_from_cache(ticket_ids)
    else:
        # All cached tickets
        print("⚠️  WARNING: This will update ALL cached tickets!")
        confirm = input("Continue? (yes/no): ")
        if confirm.lower() == 'yes':
            update_freshservice_from_cache()
        else:
            print("❌ Cancelled")